# Generated by Django 4.1.1 on 2022-09-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('e_name', models.CharField(max_length=200)),
                ('e_salary', models.IntegerField()),
                ('e_dept', models.CharField(max_length=200)),
            ],
        ),
    ]
