# Generated by Django 4.1.1 on 2022-09-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='e_salary',
        ),
    ]
